import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Nav from "@/components/nav/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TodoDND",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className}  min-h-screen `}>
          <Nav />
          <main className=" flex flex-col items-center justify-between relative  overflow-hidden ">
            {" "}
            {children}
            {/* <FuzzyOverlay /> */}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
